language: node_js
services:
  - xvfb
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '8'
before_script:
  - npm prune
script:
  - npm run test:single
after_success:
  - npm run semantic-release
branches:
  only:
    - master
